name: Todo List - Sonar , Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarQube Scan (Windows Local)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          "C:\Users\DHIYANESH\OneDrive\Desktop\GuhaTek\CICD\sonarqube-25.4.0.105899\sonar-scanner-7.1.0.4889-windows-x64\bin\sonar-scanner.bat" ^
            -Dsonar.host.url=%SONAR_HOST_URL% ^
            -Dsonar.token=%SONAR_TOKEN%
        shell: cmd
